### PR TITLE
Fix approx grad computations in w2-implementation notebook

### PR DESCRIPTION
**Pull request by csuter**
Pull request on a plane!

### CODE REVIEW

**Comment by csuter** [comment]
Actually this is wrong -- it exp's the mean parameter, which should be unconstrained.

**Comment by csuter** [comment]
Ok, fixed the mean parameter thing. Also noticed that the grad w.r.t. sigma was partly incorrect. assertion now passes.

**Comment by csuter** [comment]
Squashed 2 commits into 1.

**Comment by patrickmineault** [comment]
Grads are hard. Approve.

**Pull request merged**
